/*
-- MySQL Script generated by MySQL Workbench
-- Sun Oct 10 12:47:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Krishna_sql
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Krishna_sql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Krishna_sql` DEFAULT CHARACTER SET utf8 ;
USE `Krishna_sql` ;

-- -----------------------------------------------------
-- Table `Krishna_sql`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Krishna_sql`.`Usuario` (
  `id_u` INT NOT NULL AUTO_INCREMENT,
  `name_u` VARCHAR(45) NOT NULL,
  `email_u` VARCHAR(45) NOT NULL,
  `pass_u` VARCHAR(45) NOT NULL,
  `key_u` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id_u`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Krishna_sql`.`Dominio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Krishna_sql`.`Dominio` (
  `id_d` INT NOT NULL AUTO_INCREMENT,
  `name_d` VARCHAR(45) NOT NULL,
  `dom_d` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_d`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Krishna_sql`.`Contraseña`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Krishna_sql`.`Contraseña` (
  `id_c` INT NOT NULL AUTO_INCREMENT,
  `id_u` INT NOT NULL,
  `id_d` INT NOT NULL,
  `pass_c` VARCHAR(45) NOT NULL,
  `safe_c` TINYINT NOT NULL,
  `user_c` VARCHAR(45) NULL,
  PRIMARY KEY (`id_c`),
  INDEX `id_u_idx` (`id_u` ASC) VISIBLE,
  INDEX `id_d_idx` (`id_d` ASC) VISIBLE,
  CONSTRAINT `id_u`
    FOREIGN KEY (`id_u`)
    REFERENCES `Krishna_sql`.`Usuario` (`id_u`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_d`
    FOREIGN KEY (`id_d`)
    REFERENCES `Krishna_sql`.`Dominio` (`id_d`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
*/